# Generated by Django 5.2.8 on 2025-11-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Dinner', 'Dinner'), ('Snacks', 'Snacks'), ('Desserts', 'Desserts'), ('Healthy', 'Healthy'), ('Beverages', 'Beverages')], default='Desserts', max_length=20),
            preserve_default=False,
        ),
    ]
